apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-prediction-api
  labels:
    app: churn-prediction-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-prediction-api
  template:
    metadata:
      labels:
        app: churn-prediction-api
    spec:
      containers:
      - name: churn-prediction-api
        image: gcr.io/bankchurnpredict/churn-prediction-api:v1
        ports:
        - containerPort: 8001
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5 